### ISSUE TITLE
Loading saved weights causes issue with number of elements in batch_normalization

### ISSUE THREAD

**Issue by alexstoken** [simon-larsson/keras-swa#1]
Hi, 

Great package. I'm implementing it with [keras-yolo3](https://github.com/qqwweee/keras-yolo3) and got the error: 

`ValueError: Layer #1 (named "batch_normalization_1" in the current model) was found to correspond to layer batch_normalization_1 in the save file. However the new layer batch_normalization_1 expects 4 weights, but the saved weights have 6 elements.`

I saved the model using two methods and have tried loading it using both methods (full model with `keras.load_model()` and `model.load_weights()` as well, with the same error both times:

**Saving**
`ml_utils.save_model(model, hist_stage4, 'yolo_finetune_swa', show_plots=False)
model.save_weights(log_dir + 'trained_weights_final_swa.h5')`

**Loading**
`        try:
            self.yolo_model = load_model(model_path, compile=False)
        except:
            self.yolo_model = tiny_yolo_body(Input(shape=(None,None,3)), num_anchors//2, num_classes) \
                if is_tiny_version else yolo_body(Input(shape=(None,None,3)), num_anchors//3, num_classes)
            self.yolo_model.load_weights(self.model_path) # make sure model, anchors and classes match`

Looking through your package, I would guess the issue is in _reset_batch_norm., but I can't quite figure out what it is. 

I'm using Keras 2.1 and TF1.14., and using swa.keras.

**Comment by simon-larsson** [comment]
Hi Alex,

Thank you for the kind words regarding the package. I am traveling right now, so I am somewhat limited in what I can do, but I will try my best to help you out.

I imagine Tensorflow does not like the fact that I'm re-initializing the batch norm layers after training is started.

Send an email to [larssonsimon0@gmail.com](mailto:larssonsimon0@gmail.com) and we'll see what we can do.

**Comment by simon-larsson** [comment]
This was fixed by [Alex](https://github.com/alexstoken) himself in the PR above and was released with [version 0.1.3](https://pypi.org/project/keras-swa/0.1.3/)
