### ISSUE TITLE
Example using Tensorflow Keras fails  

### ISSUE THREAD

**Issue by csteel45** [simon-larsson/keras-swa#7]
Trying to run both examples, the Keras example works fine, but the Tensorflow Keras example fails with the output below when running in Jupyter Notebook on a Windows 10-based machine with Tensorflow version: 2.2.0 Keras version:" 2.3.0-tf. 

32/32 [==============================] - ETA: 0s - loss: 0.4727 - lr: 0.00 - ETA: 0s - loss: 0.3772 - lr: 0.00 - 0s 3ms/step - loss: 0.4227 - lr: 0.0013
Epoch 99/100
32/32 [==============================] - ETA: 0s - loss: 0.6698 - lr: 0.00 - ETA: 0s - loss: 0.4079 - lr: 0.00 - 0s 3ms/step - loss: 0.4069 - lr: 0.0027

Epoch 00100: final model weights set to stochastic weight average

Epoch 00100: reinitializing batch normalization layers

Epoch 00100: running forward pass to adjust batch normalization
Epoch 100/100
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-275-3ba2469b5d83> in <module>
     37 
     38 # train
---> 39 model.fit(X, y, epochs=epochs, verbose=1, callbacks=[swa])

~\Anaconda3\envs\imagitunes\lib\site-packages\tensorflow\python\keras\engine\training.py in _method_wrapper(self, *args, **kwargs)
     64   def _method_wrapper(self, *args, **kwargs):
     65     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
---> 66       return method(self, *args, **kwargs)
     67 
     68     # Running inside `run_distribute_coordinator` already.

~\Anaconda3\envs\imagitunes\lib\site-packages\tensorflow\python\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
    845                 step_num=step,
    846                 batch_size=batch_size):
--> 847               callbacks.on_train_batch_begin(step)
    848               tmp_logs = train_function(iterator)
    849               # Catch OutOfRangeError for Datasets of unknown size.

~\Anaconda3\envs\imagitunes\lib\site-packages\tensorflow\python\keras\callbacks.py in on_train_batch_begin(self, batch, logs)
    377     if self._should_call_train_batch_hooks:
    378       logs = self._process_logs(logs)
--> 379       self._call_batch_hook(ModeKeys.TRAIN, 'begin', batch, logs=logs)
    380 
    381   def on_train_batch_end(self, batch, logs=None):

~\Anaconda3\envs\imagitunes\lib\site-packages\tensorflow\python\keras\callbacks.py in _call_batch_hook(self, mode, hook, batch, logs)
    296     for callback in self.callbacks:
    297       batch_hook = getattr(callback, hook_name)
--> 298       batch_hook(batch, logs)
    299     self._delta_ts[hook_name].append(time.time() - t_before_callbacks)
    300 

~\Anaconda3\envs\imagitunes\lib\site-packages\tensorflow\python\keras\callbacks.py in on_train_batch_begin(self, batch, logs)
    599     """
    600     # For backwards compatibility.
--> 601     self.on_batch_begin(batch, logs=logs)
    602 
    603   @doc_controls.for_subclass_implementers

~\Anaconda3\envs\imagitunes\lib\site-packages\swa\tfkeras.py in on_batch_begin(self, batch, logs)
    113         if self.is_batch_norm_epoch:
    114 
--> 115             batch_size = self.params['samples']
    116             momentum = batch_size / (batch*batch_size + batch_size)
    117 

KeyError: 'samples'

**Comment by simon-larsson** [comment]
Seems that Tensorflow 2.2.0 version of Keras did not keep track of the number of training samples in the training parameters.

Upgrade Tensorflow to 2.3.0 and things should work.

**Comment by mehrtash** [comment]
I can confirm the same error on Tensorflow 2.3.0

~/anaconda3/envs/tf2-gpu/lib/python3.8/site-packages/swa/tfkeras.py in on_batch_begin(self, batch, logs)
    113         if self.is_batch_norm_epoch:
    114 
--> 115             batch_size = self.params['samples']
    116             momentum = batch_size / (batch*batch_size + batch_size)
    117 

KeyError: 'samples'

**Comment by mehrtash** [comment]
Using Keras API gives the following error:

~/anaconda3/envs/tf2-gpu/lib/python3.8/site-packages/swa/keras.py in on_train_begin(self, logs)
     86 
     87         if self.has_batch_norm and self.batch_size is None:
---> 88             raise ValueError('"batch_size" needs to be set for the Keras API for '
     89                              'models with batch normalization.')
     90 

ValueError: "batch_size" needs to be set for the Keras API for models with batch normalization.

**Comment by simon-larsson** [comment]
@mehrtash

That's odd. I can reproduce the error in 2.2.0 but it runs just fine for me with 2.3.0. I will share a Google Colab with this example working with tf 2.3.0.

As for the Keras API, you need to supply `batch_size` to the SWA callback if your model has a batch norm layer. This is different from the Tensorflow Keras API where callbacks have access to the batch size internally.

So add:
```
batch_size = 32

swa = SWA(... batch_size=batch_size)

model.fit(... batch_size=batch_size)
```

Please try [this colab](https://colab.research.google.com/drive/1nbHYyMM84pBKgKvNGcfdhffCtn5tIZZf?usp=sharing) with both scenarios running. Let me know if there are issues. :)

**Comment by mehrtash** [comment]
I confirm that the keras example works with tf 2.3.1 and keras 2.4.3.
The example works with and without BN.

**Comment by simon-larsson** [comment]
@mehrtash, thanks for the feedback! Will close this issue now.
