### ISSUE TITLE
KeyError: 'samples'

### ISSUE THREAD

**Issue by Gorodecki** [simon-larsson/keras-swa#8]
Hello, i'm run your code in Google Colab.

Epoch 00100: final model weights set to stochastic weight average

Epoch 00100: reinitializing batch normalization layers

Epoch 00100: running forward pass to adjust batch normalization
Epoch 100/100
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-12-0ae802e0e3ac> in <module>()
     12 
     13 # train
---> 14 model.fit(X, y, epochs=epochs, verbose=1, callbacks=[swa])

7 frames
/usr/local/lib/python3.6/dist-packages/swa/tfkeras.py in on_batch_begin(self, batch, logs)
    113         if self.is_batch_norm_epoch:
    114 
--> 115             batch_size = self.params['samples']
    116             momentum = batch_size / (batch*batch_size + batch_size)
    117 

KeyError: 'samples'
![Screenshot_198](https://user-images.githubusercontent.com/60197702/96864733-8b8bff80-1471-11eb-9e98-75e93b323673.png)

**Comment by simon-larsson** [comment]
I just re-ran the [colab](https://colab.research.google.com/drive/1nbHYyMM84pBKgKvNGcfdhffCtn5tIZZf?usp=sharing) with no errors. Feels like you have a different version of tensorflow somehow.

What is the output if you run `print(tf.__version__)`?

**Comment by Gorodecki** [comment]
2.3.0
https://colab.research.google.com/drive/1seWkFv8C8_rahwu1-lCOo5ALHQ-9q3-t?usp=sharing

**Comment by Gorodecki** [comment]
![Screenshot_199](https://user-images.githubusercontent.com/60197702/96873184-4968bb00-147d-11eb-945c-0f18212e60e3.png)
I diff notebook.

I copied your code from README.md

**Comment by simon-larsson** [comment]
This seems to be an issue. Will looking into making so this does not matter. :)
